import os
from pathlib import Path
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn

console = Console()

EXAMPLE_PIPELINE_CONTENT = """import polars as pl
from kipo.core.decorators import step
from kipo.core.definitions import DataLayer

# Simulating a pipeline
print("--- Starting Example Pipeline ---")

@step(layer=DataLayer.BRONZE, name="Load Data")
def load_data():
    # Simulate loading data
    df = pl.DataFrame({"id": [1, 2, 3], "val": [10, 20, 30]})
    return df

@step(layer=DataLayer.SILVER)
def process_data(df: pl.DataFrame):
    return df.with_columns((pl.col("val") * 2).alias("val_x2"))

@step(layer=DataLayer.GOLD)
def final_step():
    print("Pipeline finished successfully")

if __name__ == "__main__":
    df = load_data()
    process_data(df)
    final_step()
"""

GITIGNORE_CONTENT = """
# Kipo Data Directory
data/raw/*
data/bronze/*
data/silver/*
data/gold/*
!data/raw/.gitkeep
!data/bronze/.gitkeep
!data/silver/.gitkeep
!data/gold/.gitkeep

# Python
__pycache__/
*.py[cod]
.venv/
.env
"""

README_CONTENT = """# Kipo Project

This project was generated by Kipo Framework.

## Structure

- `pipelines/`: Place your ETL pipelines here.
- `data/`: Data storage separated by layers (Raw, Bronze, Silver, Gold).
- `kipo_config.toml`: Project configuration.

## Usage

Run the example pipeline:
```bash
python pipelines/example_pipeline.py
```
"""

def init_project(project_name: str):
    """
    Scaffolds a new Kipo project structure.
    """
    base_path = Path.cwd() / project_name

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        transient=True,
    ) as progress:
        task = progress.add_task(description=f"Creating project {project_name}...", total=None)

        # Create directories
        dirs_to_create = [
            base_path / "data" / "raw",
            base_path / "data" / "bronze",
            base_path / "data" / "silver",
            base_path / "data" / "gold",
            base_path / "pipelines",
        ]

        for dir_path in dirs_to_create:
            dir_path.mkdir(parents=True, exist_ok=True)
            # Create .gitkeep in data directories
            if "data" in dir_path.parts:
                 (dir_path / ".gitkeep").touch()

        # Create files
        (base_path / "pipelines" / "example_pipeline.py").write_text(EXAMPLE_PIPELINE_CONTENT, encoding="utf-8")
        (base_path / "kipo_config.toml").write_text("# Kipo Configuration\n", encoding="utf-8")
        (base_path / ".gitignore").write_text(GITIGNORE_CONTENT, encoding="utf-8")
        (base_path / "README.md").write_text(README_CONTENT, encoding="utf-8")
        
        progress.update(task, completed=100)

    console.print(f"[bold green]✅ Project '{project_name}' created successfully![/bold green]")
    console.print("\n[bold]Next steps:[/bold]")
    console.print(f"  cd {project_name}")
    console.print("  python pipelines/example_pipeline.py")
